{
 "description": "osoc service dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "[ $namespace ] Basic metrics ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers ready",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (container) (kube_pod_container_status_ready{namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Containers waiting",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (container) (kube_pod_container_status_waiting{namespace=~\"$namespace\",pod=~\"$pod\"})",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Pods count quota",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kube_resourcequota{namespace=~\"$namespace\",resource=\"pods\"}",
       "legendFormat": "usage"
      },
      {
       "expr": "kube_resourcequota{namespace=~\"$namespace\",resource=\"pods\",type=\"hard\"} * 0.8",
       "legendFormat": "threshold1"
      }
     ]
    },
    {
     "title": "Req.CPU quota",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kube_resourcequota{namespace=~\"$namespace\",resource=\"requests.cpu\"}",
       "legendFormat": "usage"
      },
      {
       "expr": "kube_resourcequota{namespace=~\"$namespace\",resource=\"requests.cpu\",type=\"hard\"} * 0.7",
       "legendFormat": "threshold1"
      }
     ]
    },
    {
     "title": "Limits CPU quota",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kube_resourcequota{namespace=~\"$namespace\",resource=\"limits.cpu\"}",
       "legendFormat": "usage"
      },
      {
       "expr": "kube_resourcequota{namespace=~\"$namespace\",resource=\"limits.cpu\",type=\"hard\"} * 0.7",
       "legendFormat": "threshold1"
      }
     ]
    },
    {
     "title": "Req.RAM quota (GiB)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kube_resourcequota{namespace=~\"$namespace\",resource=\"requests.memory\"} / 1024 / 1024 / 1024",
       "legendFormat": "usage"
      },
      {
       "expr": "(kube_resourcequota{namespace=~\"$namespace\",resource=\"requests.memory\",type=\"hard\"} * 0.8 ) / 1024 / 1024 / 1024",
       "legendFormat": "threshold1"
      }
     ]
    },
    {
     "title": "Limits RAM quota (GiB)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kube_resourcequota{namespace=~\"$namespace\",resource=\"limits.memory\"} / 1024 / 1024 / 1024",
       "legendFormat": "usage"
      },
      {
       "expr": "(kube_resourcequota{namespace=~\"$namespace\",resource=\"limits.memory\",type=\"hard\"} * 0.8 ) / 1024 / 1024 / 1024",
       "legendFormat": "threshold1"
      }
     ]
    },
    {
     "title": "Req. storage quota (GiB)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "kube_resourcequota{namespace=~\"$namespace\",resource=\"requests.storage\"} / 1024 / 1024 / 1024",
       "legendFormat": "usage"
      },
      {
       "expr": "(kube_resourcequota{namespace=~\"$namespace\",resource=\"requests.storage\",type=\"hard\"} * 0.8 ) / 1024 / 1024 / 1024",
       "legendFormat": "threshold1"
      }
     ]
    },
    {
     "title": "Container restarts",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (container) (increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$pod\"}[$__range]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "CPU (real)",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{pod}}-{{container}}"
      },
      {
       "expr": "kube_pod_container_resource_limits{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",resource=\"cpu\"}",
       "legendFormat": "{{pod}}-{{container}}-limit"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{namespace=~\"$namespace\",container=~\"$container\"}",
       "legendFormat": "{{container}}:{{pod}}"
      },
      {
       "expr": "container_spec_memory_limit_bytes{namespace=~\"$namespace\",container=~\"$container\"}",
       "legendFormat": "OOM:{{container}}:{{pod}}"
      }
     ]
    },
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} - RX"
      },
      {
       "expr": "- irate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval])",
       "legendFormat": "{{pod}} - TX"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "container_processes{namespace=~\"$namespace\",container=~\"$container\"}",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 19 },
     "targets": [
      {
       "expr": "container_threads{namespace=~\"$namespace\",container=~\"$container\"}",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    },
    {
     "title": "File descriptors",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 19 },
     "targets": [
      {
       "expr": "container_file_descriptors{namespace=~\"$namespace\",container=~\"$container\"}",
       "legendFormat": "{{pod}}-{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $namespace ] Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Success Rate (non-4|5xx responses) in $namespace",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n    sum by (namespace,ingress) (rate(nginx_ingress_controller_requests{namespace=~\"$namespace\",status!~\"[4-5].*\"}[$__rate_interval])) \n    / \n    sum by (namespace,ingress) (rate(nginx_ingress_controller_requests{namespace=~\"$namespace\"}[$__rate_interval]))\n) >=0",
       "legendFormat": "{{ingress}}"
      }
     ]
    },
    {
     "title": "Ingress requests in $namespace",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "round(sum(irate(nginx_ingress_controller_requests{namespace=~\"$namespace\"}[$__rate_interval])) by (ingress), 0.001)",
       "legendFormat": "{{ingress}}"
      }
     ]
    },
    {
     "title": "Ingress timings in $namespace",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",namespace=~\"$namespace\"}[$__rate_interval])) by (le, ingress)) >= 0",
       "legendFormat": "{{ingress}} - 50 pcntl"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",namespace=~\"$namespace\"}[$__rate_interval])) by (le, ingress)) >= 0",
       "legendFormat": "{{ingress}} - 90 pcntl"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",namespace=~\"$namespace\"}[$__rate_interval])) by (le, ingress)) >= 0",
       "legendFormat": "{{ingress}} - 95 pcntl"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",namespace=~\"$namespace\"}[$__rate_interval])) by (le, ingress)) >= 0",
       "legendFormat": "{{ingress}} - 99 pcntl"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",namespace=~\"$namespace\"}[$__rate_interval])) by (le, ingress)) >= 0",
       "legendFormat": "{{ingress}} - 100 pcntl"
      }
     ]
    },
    {
     "title": "Ingress traffic in $namespace",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(irate(nginx_ingress_controller_request_size_sum{ingress!=\"\",namespace=~\"$namespace\"}[$__rate_interval])) by (ingress)",
       "legendFormat": "{{ingress}} - RX"
      },
      {
       "expr": "- sum(irate(nginx_ingress_controller_response_size_sum{ingress!=\"\",namespace=~\"$namespace\"}[$__rate_interval])) by (ingress)",
       "legendFormat": "{{ingress}} - TX"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $namespace ] Business metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Total RPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(rate(osoc_requests_total[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS per handler",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 3 },
   "targets": [
    {
     "expr": "round(sum by(handler) (rate(osoc_requests_total{handler!=\"\"}[$__rate_interval])))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(osoc_requests_total{code=~\"4..|5..\", handler!=\"\"}[$__rate_interval])) by(handler) / sum(rate(osoc_requests_total{handler!=\"\"}[$__rate_interval])) by(handler) * 100",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(handler)(rate(osoc_requests_duration_sum{code=~\"2..\", handler!=\"\"}[$__rate_interval])) / sum by(handler) (rate(osoc_requests_duration_count{code=~\"2..\", handler!=\"\"}[$__rate_interval])) * 1000",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "RPS per instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(rate(osoc_requests_total[$__rate_interval])) by (pod))",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}