// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"osoc/internal/api/http/v1"
	"osoc/internal/config"
	"osoc/internal/repository/user"
	"osoc/internal/repository/webdata"
	"osoc/internal/serviceprovider"
	"osoc/internal/usecase/secure"
	"osoc/internal/usecase/userinfo"
	"osoc/pkg/application"
)

// Injectors from wire.go:

func newApp() (*application.App, func(), error) {
	configConfig, err := config.GetConfig()
	if err != nil {
		return nil, nil, err
	}
	buildVersion, err := application.GetBuildVersion()
	if err != nil {
		return nil, nil, err
	}
	logger := serviceprovider.NewLogger(configConfig, buildVersion)
	app := config.GetAppConfig(configConfig)
	daemon := userinfo.NewDaemon(logger, app)
	engine := serviceprovider.NewBaseRouter(configConfig, logger, buildVersion, daemon)
	mysql := config.GetMysqlConfig(configConfig)
	db, cleanup, err := serviceprovider.NewMysql(mysql)
	if err != nil {
		return nil, nil, err
	}
	secureRepo := user.NewSecureRepo(db)
	auth := secure.NewAuth(logger, secureRepo, app)
	slaveMysql, cleanup2, err := serviceprovider.NewSlaveMysql()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repository := user.New(db, slaveMysql)
	service := userinfo.NewService(repository, logger)
	webData := webdata.NewWebData(repository, logger)
	handler := v1.NewRouter(engine, configConfig, auth, service, logger, webData)
	server := serviceprovider.NewHttp(handler, configConfig, logger)
	promConfig := config.GetPrometheusConfig(configConfig)
	promServer := serviceprovider.NewPrometheus(promConfig, logger)
	applicationApp := createApp(server, promServer, configConfig, logger)
	return applicationApp, func() {
		cleanup2()
		cleanup()
	}, nil
}
